import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { Readable } from 'node:stream';
import { Pool } from 'pg';
import { describe, expect, it } from 'vitest';
import type { ResourceChangeEvent, ResourceChangeListener } from '../../src/storage/ObservableResourceStore';
import {
  type DurableResourceChangeConsumer,
  PostgresDerivedIndexJournal,
  type PostgresDerivedIndexJournalOptions,
} from '../../src/storage/PostgresDerivedIndexJournal';
import { PgliteRdfSqlExecutor } from '../../src/storage/rdf/PostgresRdfSqlExecutor';
import { PgPoolRdfSqlExecutor } from '../../src/storage/rdf/PostgresRdfSqlExecutor';
import { PostgresRdfTextIndex } from '../../src/storage/rdf/PostgresRdfTextIndex';
import { PostgresRdfVectorIndex } from '../../src/storage/rdf/PostgresRdfVectorIndex';
import { RdfDerivedIndexingListener } from '../../src/storage/RdfDerivedIndexingListener';

async function waitUntil(predicate: () => boolean, timeoutMs: number): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (!predicate()) {
    if (Date.now() >= deadline) {
      throw new Error(`condition was not met within ${timeoutMs}ms`);
    }
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
}

describe('PostgresDerivedIndexJournal', () => {
  it('rejects empty and duplicate configured consumer IDs', () => {
    const db = new PGlite();
    expect(() => createJournal({
      executor: new PgliteRdfSqlExecutor(db),
      consumers: [consumer('', [])],
    })).toThrow('non-empty consumerId');
    expect(() => createJournal({
      executor: new PgliteRdfSqlExecutor(db),
      consumers: [consumer('search-v1', []), consumer('search-v1', [])],
    })).toThrow('Duplicate derived-index consumerId: search-v1');
  });

  it('delivers changes in sequence within each Pod', async () => {
    const db = new PGlite();
    const journal = createJournal({
      executor: new PgliteRdfSqlExecutor(db),
      resolvePodScope: (event) => event.path.split('/')[1]!,
    });
    await journal.open();
    await journal.recordResourceChange(event('/alice/2'));
    await journal.recordResourceChange(event('/bob/1'));
    await journal.recordResourceChange(event('/alice/3'));

    const delivered: string[] = [];
    const listener: ResourceChangeListener = {
      onResourceChanged: async (change) => { delivered.push(change.path); },
    };
    expect(await journal.replayPending(listener)).toMatchObject({ delivered: 3, failed: 0 });
    expect(delivered.indexOf('/alice/2')).toBeLessThan(delivered.indexOf('/alice/3'));
  });

  it('keeps a failed head pending and does not overtake it within the Pod', async () => {
    const db = new PGlite();
    const journal = createJournal({
      executor: new PgliteRdfSqlExecutor(db),
      resolvePodScope: () => 'alice',
      retryDelayMs: 60_000,
    });
    await journal.open();
    await journal.recordResourceChange(event('/alice/1'));
    await journal.recordResourceChange(event('/alice/2'));

    const delivered: string[] = [];
    const listener: ResourceChangeListener = {
      onResourceChanged: async (change) => {
        delivered.push(change.path);
        throw new Error('index unavailable');
      },
    };
    expect(await journal.replayPending(listener)).toMatchObject({ delivered: 0, failed: 1 });
    expect(delivered).toEqual(['/alice/1']);
    expect(await journal.pendingCount('alice')).toBe(2);
  });

  it('enqueues an authority snapshot for bootstrap self-healing', async () => {
    const db = new PGlite();
    const journal = createJournal({
      executor: new PgliteRdfSqlExecutor(db),
      resolvePodScope: () => 'alice',
    });
    await journal.open();
    await journal.reconcilePod('alice', ['/alice/a.md', '/alice/b.ttl']);
    expect(await journal.pendingCount('alice')).toBe(2);
  });

  it('backfills existing RDF authority sources once when the journal is first installed', async () => {
    const db = new PGlite();
    const executor = new PgliteRdfSqlExecutor(db);
    await executor.exec(`
      CREATE TABLE rdf_sources (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source TEXT NOT NULL UNIQUE,
        workspace TEXT NOT NULL
      );
      INSERT INTO rdf_sources (source, workspace) VALUES
        ('https://pod.example/alice/a.ttl', 'https://pod.example/alice/'),
        ('https://pod.example/bob/b.ttl', 'https://pod.example/bob/');
    `);

    const firstProcess = createJournal({ executor });
    await firstProcess.open();
    expect(await firstProcess.pendingCount()).toBe(2);
    await firstProcess.close();

    const restartedProcess = createJournal({ executor });
    await restartedProcess.open();
    expect(await restartedProcess.pendingCount()).toBe(2);
    await restartedProcess.close();
  });

  it('defers the bootstrap marker until the RDF authority table exists', async () => {
    const db = new PGlite();
    const executor = new PgliteRdfSqlExecutor(db);
    const earlyJournal = createJournal({ executor });
    await earlyJournal.open();
    await earlyJournal.close();
    await executor.exec(`
      CREATE TABLE rdf_sources (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source TEXT NOT NULL UNIQUE,
        workspace TEXT NOT NULL
      );
      INSERT INTO rdf_sources (source, workspace)
      VALUES ('https://pod.example/alice/late.ttl', 'https://pod.example/alice/');
    `);

    const readyJournal = createJournal({ executor });
    await readyJournal.open();
    expect(await readyJournal.pendingCount()).toBe(1);
    await readyJournal.close();
  });

  it('is the single durable recorder around the cloud ResourceStore backend', async () => {
    const cloud = JSON.parse(await readFile(path.join(process.cwd(), 'config/cloud.json'), 'utf8'));
    const graph = cloud['@graph'] as Array<Record<string, any>>;
    const journal = graph.find((entry) => entry['@id'] === 'urn:undefineds:xpod:DerivedIndexChangeJournal');
    const override = graph.find((entry) => entry.overrideInstance?.['@id'] === 'urn:solid-server:default:ResourceStore_Backend');
    expect(journal).toMatchObject({ '@type': 'PostgresDerivedIndexJournal' });
    expect(journal.consumers).toEqual([
      { '@id': 'urn:undefineds:xpod:RdfDerivedIndexingListener' },
    ]);
    expect(graph.find((entry) => entry['@id'] === 'urn:undefineds:xpod:RdfDerivedIndexingListener'))
      .toMatchObject({
        '@type': 'RdfDerivedIndexingListener',
        rdfEngine: { '@id': 'urn:undefineds:xpod:SolidRdfEngine' },
      });
    expect(override?.overrideParameters).toMatchObject({
      '@type': 'ObservableResourceStore',
      options_recorders: [{ '@id': 'urn:undefineds:xpod:DerivedIndexChangeJournal' }],
    });
    expect(JSON.stringify(override)).not.toContain('SqliteSolidFsSyncJournal');
  });

  it('replays automatically after construction and recovers an expired processing lease', async () => {
    const db = new PGlite();
    const executor = new PgliteRdfSqlExecutor(db);
    const firstProcess = createJournal({
      executor,
      resolvePodScope: () => 'alice',
    });
    await firstProcess.open();
    await firstProcess.recordResourceChange(event('/alice/recover.md'));
    await executor.exec(`
      UPDATE derived_index_change_journal
      SET stage = 'processing', lease_until = 0
      WHERE resource_path = '/alice/recover.md'
    `);
    await firstProcess.close();

    const delivered: string[] = [];
    const journal = createJournal({
      executor,
      resolvePodScope: () => 'alice',
      pollIntervalMs: 10,
      consumers: [consumer('recovery-v1', delivered)],
    });

    await waitUntil(() => delivered.length === 1, 2_000);
    expect(delivered).toEqual(['/alice/recover.md']);
    expect(await journal.pendingCount('alice')).toBe(0);
    await journal.close();
  });

  const liveIt = process.env.XPOD_DERIVED_INDEX_PG_DSN ? it : it.skip;
  liveIt('persists and retrieves FTS/VEC derivations through PostgreSQL 17', async () => {
    const connectionString = process.env.XPOD_DERIVED_INDEX_PG_DSN!;
    const pool = new Pool({ connectionString });
    const executor = new PgPoolRdfSqlExecutor(pool);
    const textIndex = new PostgresRdfTextIndex({ driver: 'pg', pool });
    const vectorIndex = new PostgresRdfVectorIndex({ driver: 'pg', pool, backend: 'component' });
    await textIndex.open();
    await vectorIndex.open();
    const engine = {
      indexTextSource: (source: any, text: string) => textIndex.indexText(source, text),
      deleteTextSource: (source: string) => textIndex.deleteSource(source),
      indexVectorSource: (source: any, chunks: any[]) => vectorIndex.indexVector(source, chunks),
      deleteVectorSource: (source: string) => vectorIndex.deleteSource(source),
    };
    const listener = createDerivedListener({
      rdfEngine: engine,
      resourceStore: {
        getRepresentation: async () => ({
          data: Readable.from(['durable postgres retrieval']),
          metadata: { contentType: 'text/markdown' },
        }),
      } as any,
      embeddingService: { embedBatch: async () => [[1, 0]] } as any,
      resolveCredential: async () => ({ apiKey: 'test', provider: 'test' }),
      defaultModel: 'test-model',
    });
    const journal = createJournal({
      executor,
      resolvePodScope: () => 'https://pod.example/alice/',
    });
    await journal.open();
    await journal.recordResourceChange(event('https://pod.example/alice/doc.md'));
    expect(await journal.replayPending(listener)).toMatchObject({ delivered: 1, failed: 0 });
    expect((await textIndex.search({ query: 'postgres retrieval', workspace: 'https://pod.example/alice/' }))[0]?.source)
      .toBe('https://pod.example/alice/doc.md');
    expect((await vectorIndex.search({ embedding: [1, 0], workspace: 'https://pod.example/alice/' }))[0]?.source)
      .toBe('https://pod.example/alice/doc.md');
    await pool.end();
  });
});

function event(path: string): ResourceChangeEvent {
  return { path, action: 'update', isContainer: false, timestamp: Date.now() };
}

function consumer(
  consumerId: string,
  delivered: string[],
  options: { failOnce?: boolean } = {},
): DurableResourceChangeConsumer {
  let shouldFail = options.failOnce ?? false;
  return {
    consumerId,
    onResourceChanged: async (change) => {
      delivered.push(change.path);
      if (shouldFail) {
        shouldFail = false;
        throw new Error(`${consumerId} unavailable`);
      }
    },
  };
}

function createJournal(options: PostgresDerivedIndexJournalOptions): PostgresDerivedIndexJournal {
  return new PostgresDerivedIndexJournal(
    options.connectionString,
    options.executor,
    options.resolvePodScope,
    options.retryDelayMs,
    options.leaseMs,
    options.consumers,
    options.pollIntervalMs,
  );
}

function createDerivedListener(options: any): RdfDerivedIndexingListener {
  return new RdfDerivedIndexingListener(
    options.rdfEngine,
    options.resourceStore,
    options.embeddingService,
    options.sparqlEngine,
    options.resolveCredential,
    options.defaultModel,
    options.supportedExtensions,
  );
}
