{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "xpod-cloud-storage",
    "namespace": "ns-iknkxtc8"
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    },
    "storageClassName": "openebs-lvmpv",
    "volumeMode": "Filesystem",
    "volumeName": "pvc-4b010762-a51c-4eb2-a192-950e74194050"
  }
}
