import { createHash, randomUUID } from 'node:crypto';
import type {
  CreateServiceTokenOptions,
  ServiceTokenRecord,
  ServiceTokenRepositoryPort,
  ServiceType,
} from '../identity/drizzle/ServiceTokenRepository';

export interface LocalSetupServiceTokenRepositoryOptions {
  token?: string;
  serviceType: ServiceType;
  serviceId: string;
  scopes: string[];
}

export class LocalSetupServiceTokenRepository implements ServiceTokenRepositoryPort {
  private record: ServiceTokenRecord | undefined;
  private tokenHash: string | undefined;

  public constructor(options: LocalSetupServiceTokenRepositoryOptions) {
    if (!options.token) {
      return;
    }
    this.tokenHash = this.hashToken(options.token);
    this.record = {
      id: `local-setup-${options.serviceType}-${options.serviceId}`,
      serviceType: options.serviceType,
      serviceId: options.serviceId,
      scopes: options.scopes,
      createdAt: new Date(),
      expiresAt: null,
    };
  }

  public async createToken(_options: CreateServiceTokenOptions): Promise<{ id: string; token: string }> {
    throw new Error('Local setup service tokens are supplied by setup, not generated by the API');
  }

  public async registerToken(token: string, options: CreateServiceTokenOptions): Promise<string> {
    const id = this.record?.id ?? `local-setup-${randomUUID()}`;
    this.tokenHash = this.hashToken(token);
    this.record = {
      id,
      serviceType: options.serviceType,
      serviceId: options.serviceId,
      scopes: options.scopes,
      createdAt: this.record?.createdAt ?? new Date(),
      expiresAt: options.expiresAt ?? null,
    };
    return id;
  }

  public async verifyToken(token: string): Promise<ServiceTokenRecord | undefined> {
    if (!this.record || !this.tokenHash) {
      return undefined;
    }
    if (this.hashToken(token) !== this.tokenHash) {
      return undefined;
    }
    if (this.record.expiresAt && this.record.expiresAt.getTime() < Date.now()) {
      return undefined;
    }
    return this.record;
  }

  public async findByService(serviceType: ServiceType, serviceId: string): Promise<ServiceTokenRecord | undefined> {
    if (this.record?.serviceType === serviceType && this.record.serviceId === serviceId) {
      return this.record;
    }
    return undefined;
  }

  public async deleteToken(id: string): Promise<void> {
    if (this.record?.id === id) {
      this.record = undefined;
      this.tokenHash = undefined;
    }
  }

  public async listTokens(): Promise<ServiceTokenRecord[]> {
    return this.record ? [this.record] : [];
  }

  private hashToken(token: string): string {
    return createHash('sha256').update(token).digest('hex');
  }
}
