{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "xpod-co-storage",
    "namespace": "ns-iknkxtc8"
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    },
    "storageClassName": "openebs-lvmpv",
    "volumeMode": "Filesystem",
    "volumeName": "pvc-c86bc1d3-fbe2-4ec3-91a9-9bdfa9c02d14"
  }
}
