apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpod-co
  name: xpod-co
  namespace: ns-iknkxtc8
spec:
  clusterIP: 10.96.101.0
  clusterIPs:
  - 10.96.101.0
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: xpod-co
  sessionAffinity: None
  type: ClusterIP
