apiVersion: v1
kind: Service
metadata:
  name: xpod-inngest
  namespace: xpod-cloud
  labels:
    app: xpod-inngest
spec:
  type: ClusterIP
  selector:
    app: xpod-inngest
  ports:
    - name: http
      port: 8288
      targetPort: http
      protocol: TCP
