/**
 * Tunnel ingress acceptance harness (W1).
 *
 * Runs the checks from docs/network-audit-w0-acceptance-plan.md that can be executed
 * without a human: it starts (or reuses) a candidate instance of the current checkout,
 * records what the candidate actually is, and then exercises the administrative isolation
 * matrix over every available entry — the loopback listener, the untrusted ingress
 * listener, and any real tunnel the operator configured.
 *
 * Secrets are read from the env file and never printed; the evidence files record only
 * status codes, URLs, timestamps and fingerprints.
 *
 * Usage:
 *   bun scripts/accept-network-tunnel.ts --candidate-port 3300 --start
 *   bun scripts/accept-network-tunnel.ts --reuse --public-url https://entry.example/
 */

import { spawn, type ChildProcess } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createFakeQleverRuntimeCommand } from '../tests/helpers/qleverRuntime';

interface Options {
  candidatePort: number;
  envFile: string;
  start: boolean;
  reuse: boolean;
  publicUrl?: string;
  ingressPort?: number;
  evidenceDir: string;
  adminToken?: string;
  timeoutMs: number;
  explicitOff: boolean;
}

interface CheckResult {
  id: string;
  entry: string;
  expectation: string;
  observed: string;
  ok: boolean;
  detail?: string;
}

function parseArgs(argv: string[]): Options {
  const options: Options = {
    candidatePort: 3300,
    envFile: path.resolve('.env.acceptance'),
    start: false,
    reuse: false,
    evidenceDir: path.resolve('.test-data/acceptance/tunnel'),
    timeoutMs: 90_000,
    explicitOff: true,
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const next = (): string => {
      index += 1;
      const value = argv[index];
      if (value === undefined) throw new Error(`${arg} requires a value`);
      return value;
    };
    switch (arg) {
      case '--candidate-port': options.candidatePort = Number(next()); break;
      case '--env-file': options.envFile = path.resolve(next()); break;
      case '--start': options.start = true; break;
      case '--reuse': options.reuse = true; break;
      case '--public-url': options.publicUrl = next(); break;
      case '--ingress-port': options.ingressPort = Number(next()); break;
      case '--evidence-dir': options.evidenceDir = path.resolve(next()); break;
      case '--admin-token': options.adminToken = next(); break;
      case '--timeout-ms': options.timeoutMs = Number(next()); break;
      case '--no-explicit-off': options.explicitOff = false; break;
      default: throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return options;
}

function loadEnvFile(file: string): Record<string, string> {
  const env: Record<string, string> = {};
  if (!existsSync(file)) return env;
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const separator = trimmed.indexOf('=');
    if (separator <= 0) continue;
    const key = trimmed.slice(0, separator).trim();
    const value = trimmed.slice(separator + 1).trim().replace(/^["']|["']$/gu, '');
    if (value) env[key] = value;
  }
  return env;
}

/** Identifier safe to print for a secret: never the value itself. */
function fingerprint(value: string | undefined): string {
  if (!value) return 'absent';
  return `sha256:${createHash('sha256').update(value).digest('hex').slice(0, 8)}`;
}

async function fetchStatus(url: string, init: RequestInit = {}): Promise<{ status: number; body: string }> {
  try {
    const response = await fetch(url, { ...init, signal: AbortSignal.timeout(15_000) });
    return { status: response.status, body: await response.text() };
  } catch (error) {
    return { status: 0, body: (error as Error).message };
  }
}

async function waitForCandidate(port: number, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const probe = await fetchStatus(`http://127.0.0.1:${port}/service/status`);
    if (probe.status === 200) return true;
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  return false;
}

interface Entry {
  id: string;
  label: string;
  baseUrl: string;
}

/**
 * Administrative isolation matrix for one entry.
 *
 * A remote entry must reject anonymous and forged-admin requests; the loopback entry must
 * still serve the local operator. `adminToken` is the candidate's own token, generated by
 * this harness, so the positive control proves the entry is not simply blocked outright.
 */
async function runIsolationMatrix(entry: Entry, adminToken: string | undefined): Promise<CheckResult[]> {
  const base = entry.baseUrl.replace(/\/$/u, '');
  const results: CheckResult[] = [];

  const anonymous = await fetchStatus(`${base}/api/admin/status`);
  results.push({
    id: 'admin-status-anonymous',
    entry: entry.id,
    expectation: entry.id === 'loopback' ? '200 (local operator)' : '403 (remote caller)',
    observed: String(anonymous.status),
    ok: entry.id === 'loopback' ? anonymous.status === 200 : anonymous.status === 403,
  });

  const forged = await fetchStatus(`${base}/api/admin/status`, {
    headers: {
      'x-xpod-admin-proxy-loopback': '1',
      'x-xpod-admin-proxy-signature': 'forged',
      'x-forwarded-for': '127.0.0.1',
      'x-forwarded-host': 'localhost',
      host: 'localhost',
    },
  });
  results.push({
    id: 'admin-status-forged-headers',
    entry: entry.id,
    expectation: entry.id === 'loopback' ? '200 (local operator)' : '403 (forged evidence rejected)',
    observed: String(forged.status),
    ok: entry.id === 'loopback' ? forged.status === 200 : forged.status === 403,
  });

  const mutation = await fetchStatus(`${base}/api/admin/config`, {
    method: 'PUT',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ env: { CSS_LOGGING_LEVEL: 'info' } }),
  });
  results.push({
    id: 'admin-config-mutation-anonymous',
    entry: entry.id,
    expectation: entry.id === 'loopback' ? '200 (local operator)' : '403 (remote caller)',
    observed: String(mutation.status),
    ok: entry.id === 'loopback' ? mutation.status === 200 : mutation.status === 403,
  });

  if (adminToken) {
    const authorised = await fetchStatus(`${base}/api/admin/status`, {
      headers: { 'x-xpod-admin-token': adminToken },
    });
    results.push({
      id: 'admin-status-explicit-token',
      entry: entry.id,
      expectation: '200 (explicitly authorised management)',
      observed: String(authorised.status),
      ok: authorised.status === 200,
    });
  }

  const ordinary = await fetchStatus(`${base}/service/status`);
  results.push({
    id: 'ordinary-route',
    entry: entry.id,
    expectation: '200 (non-admin traffic keeps working)',
    observed: String(ordinary.status),
    ok: ordinary.status === 200,
  });

  return results;
}

function readP2pEnabled(statusBody: string): boolean | undefined {
  try {
    const parsed = JSON.parse(statusBody) as { configuration?: { p2p?: { enabled?: boolean } } };
    return parsed.configuration?.p2p?.enabled;
  } catch {
    return undefined;
  }
}

interface TunnelObservation {
  provider: string;
  credential: string;
  readiness?: string;
  endpoint?: string;
  detail?: string;
}

/** The runtime prints the assigned ingress port; it is an OS-assigned internal detail. */
function readIngressPort(logFile: string): number | undefined {
  if (!existsSync(logFile)) return undefined;
  const matches = [ ...readFileSync(logFile, 'utf8').matchAll(/Ingress listener on 127\.0\.0\.1:(\d+)/gu) ];
  const last = matches.at(-1);
  return last ? Number(last[1]) : undefined;
}

function readCatalog(statusBody: string): Array<{ id: string; legacyCredentialEnvKey: string }> {
  try {
    const parsed = JSON.parse(statusBody) as { providers?: Array<{ id: string; legacyCredentialEnvKey: string }> };
    return parsed.providers ?? [];
  } catch {
    return [];
  }
}

function readTunnelCapability(statusBody: string): string | undefined {
  try {
    const parsed = JSON.parse(statusBody) as { tunnel?: { status?: string; supported?: boolean } };
    return parsed.tunnel?.supported ? parsed.tunnel.status : 'unsupported';
  } catch {
    return undefined;
  }
}

async function startCandidate(
  options: Options,
  checkout: string,
  logFile: string,
  adminToken: string,
  scratchDir: string,
  qleverCommand: string,
  port = options.candidatePort,
  extraEnv: Record<string, string> = {},
): Promise<ChildProcess> {
  const log = await import('node:fs').then(({ openSync }) => openSync(logFile, 'a'));
  const child = spawn(
    'bun',
    [
      '--no-env-file',
      path.join(checkout, 'src/cli/index.ts'),
      'start',
      '-m', 'local',
      '-p', String(port),
      '-e', options.envFile,
      '-c', path.join(checkout, 'config/local.json'),
      ...(existsSync(path.join(checkout, 'config/seed.dev.json'))
        ? [ '--seedConfig', path.join(checkout, 'config/seed.dev.json') ]
        : []),
    ],
    {
      cwd: scratchDir,
      env: {
        ...process.env,
        CSS_LOGGING_LEVEL: 'info',
        // The candidate gets a harness-owned admin token so the positive control can prove
        // the entry is not simply blocked outright.
        XPOD_ADMIN_TOKEN: adminToken,
        // The harness brings its own storage: acceptance must never touch the operator's
        // data, and the sqlite SPARQL path needs no native runtime binary.
        CSS_SPARQL_ENDPOINT: `sqlite:${path.join(scratchDir, 'sparql.sqlite')}`,
        CSS_RDF_INDEX_PATH: path.join(scratchDir, 'rdf-index.sqlite'),
        CSS_IDENTITY_DB_URL: `sqlite:${path.join(scratchDir, 'identity.sqlite')}`,
        XPOD_QLEVER_LOCAL_RUNTIME_COMMAND: qleverCommand,
        ...extraEnv,
      },
      stdio: [ 'ignore', log, log ],
    },
  );
  return child;
}

async function stopChild(child: ChildProcess | undefined): Promise<void> {
  if (!child || child.exitCode !== null) return;
  child.kill('SIGTERM');
  await new Promise((resolve) => setTimeout(resolve, 2_000));
  if (child.exitCode === null) child.kill('SIGKILL');
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));
  const checkout = path.resolve(import.meta.dir, '..');
  const env = loadEnvFile(options.envFile);
  mkdirSync(options.evidenceDir, { recursive: true });
  const scratchDir = path.join(checkout, '.test-data/acceptance/candidate');
  mkdirSync(scratchDir, { recursive: true });
  const logFile = path.join(options.evidenceDir, `candidate-${Date.now()}.log`);

  const candidateSha = (await import('node:child_process')).execSync('git rev-parse HEAD', { cwd: checkout })
    .toString().trim();
  const candidateDirty = (await import('node:child_process')).execSync('git status --porcelain', { cwd: checkout })
    .toString().trim().length > 0;

  // The candidate gets its own admin token: the positive control must not depend on the
  // operator's production secret.
  const adminToken = options.adminToken ?? `accept-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`;

  // The network and authorization layers are what this harness evaluates; when no real
  // QLever runtime is installed the storage fixture from the integration tests is used and
  // recorded as such, so the evidence never claims a real storage backend.
  const qleverFixture = process.env.XPOD_QLEVER_LOCAL_RUNTIME_COMMAND
    ? undefined
    : createFakeQleverRuntimeCommand();
  const qleverCommand = process.env.XPOD_QLEVER_LOCAL_RUNTIME_COMMAND ?? qleverFixture!.command;

  let child: ChildProcess | undefined;
  const checks: CheckResult[] = [];
  const tunnels: TunnelObservation[] = [];
  try {
    if (options.start) {
      console.log(`[accept] starting candidate on port ${options.candidatePort} (sha ${candidateSha.slice(0, 8)})`);
      child = await startCandidate(options, checkout, logFile, adminToken, scratchDir, qleverCommand);
    }
    const ready = await waitForCandidate(options.candidatePort, options.timeoutMs);
    if (!ready) {
      throw new Error(`candidate did not become ready on port ${options.candidatePort}`);
    }

    const loopbackBase = `http://127.0.0.1:${options.candidatePort}/`;
    const status = await fetchStatus(`${loopbackBase}service/status`);
    checks.push({
      id: 'candidate-runtime',
      entry: 'loopback',
      expectation: '200 with css and api running',
      observed: String(status.status),
      ok: status.status === 200 && /"css"/u.test(status.body) && /"api"/u.test(status.body),
      detail: status.body.slice(0, 400),
    });

    const networkStatus = await fetchStatus(`${loopbackBase}api/network/settings/status`);
    const catalog = readCatalog(networkStatus.body);
    const readiness = readTunnelCapability(networkStatus.body);
    writeFileSync(path.join(options.evidenceDir, 'candidate-network-status.json'), JSON.stringify({
      sha: candidateSha,
      dirty: candidateDirty,
      fetchedAt: new Date().toISOString(),
      httpStatus: networkStatus.status,
      providers: catalog,
      tunnel: readiness,
    }, null, 2));

    // 1) The loopback listener must keep serving the local operator.
    checks.push(...await runIsolationMatrix({ id: 'loopback', label: 'local listener', baseUrl: loopbackBase }, adminToken));

    // 2) The untrusted ingress listener is the origin every remote forwarder uses, so it
    //    stands in for a real tunnel when no credential is available.
    const ingressPort = options.ingressPort ?? readIngressPort(logFile);
    if (ingressPort) {
      checks.push(...await runIsolationMatrix({
        id: 'ingress',
        label: 'untrusted ingress listener',
        baseUrl: `http://127.0.0.1:${ingressPort}/`,
      }, adminToken));
    }

    // 3) A real public entry, when one is configured or declared.
    const publicEntry = options.publicUrl
      ?? env.NGROK_URL
      ?? env.CLOUDFLARE_TUNNEL_URL
      ?? env.SAKURA_TUNNEL_URL;
    if (publicEntry) {
      checks.push(...await runIsolationMatrix({ id: 'public', label: 'public entry', baseUrl: publicEntry }, adminToken));
    } else {
      checks.push({
        id: 'public-entry',
        entry: 'public',
        expectation: '403 for anonymous/forged admin requests',
        observed: 'not available',
        ok: true,
        detail: 'no public entry configured or declared; tunnel leg recorded as uncovered',
      });
    }

    // Scope isolation (A12) and the peer-to-peer default are configuration facts the
    // candidate can prove without any third-party credential.
    const catalogIds = catalog.map((provider) => provider.id);
    checks.push({
      id: 'scope-no-relay-no-tailscale',
      entry: 'candidate',
      expectation: 'no tailscale or relay provider is offered',
      observed: catalogIds.join(',') || 'none',
      ok: !catalogIds.some((id) => /tailscale|relay/iu.test(id)),
    });
    const p2pEnabled = readP2pEnabled(networkStatus.body);
    checks.push({
      id: 'p2p-opt-in-default',
      entry: 'candidate',
      expectation: 'false unless the deployment opted in',
      observed: String(p2pEnabled),
      ok: p2pEnabled === false,
    });

    // A02: an explicitly closed tunnel must stay closed even with a stored credential —
    // the check needs no real account, only a dummy credential the runtime must not use.
    if (options.explicitOff) {
      // Far enough from the first candidate: the CLI derives its CSS/API ports from the
      // gateway port, so a neighbour would collide instead of testing anything.
      const offPort = options.candidatePort + 100;
      const offLog = path.join(options.evidenceDir, `candidate-explicit-off-${Date.now()}.log`);
      const offChild = await startCandidate(options, checkout, offLog, adminToken, scratchDir, qleverCommand, offPort, {
        XPOD_TUNNEL_PROFILES: JSON.stringify([
          { id: 'accept-off', provider: 'ngrok', label: 'closed tunnel', publicUrl: 'https://closed.example.com' },
        ]),
        XPOD_TUNNEL_ACTIVE_PROFILE_ID: 'none',
        XPOD_TUNNEL_PROFILE_ACCEPT_OFF_TOKEN: 'dummy-credential-never-used',
      });
      try {
        const offReady = await waitForCandidate(offPort, options.timeoutMs);
        const offStatus = await fetchStatus(`http://127.0.0.1:${offPort}/api/network/settings/status`);
        const offTunnel = readTunnelCapability(offStatus.body);
        const offLogText = existsSync(offLog) ? readFileSync(offLog, 'utf8') : '';
        checks.push({
          id: 'explicit-off-stays-off',
          entry: 'candidate',
          expectation: 'tunnel inactive and no provider started',
          observed: `${offTunnel ?? 'unknown'}${/Starting ngrok tunnel|ngrok http/iu.test(offLogText) ? ' + provider started' : ''}`,
          ok: offReady && (offTunnel === 'inactive' || offTunnel === 'unsupported')
            && !/Starting ngrok tunnel|ngrok http/iu.test(offLogText),
        });
      } finally {
        await stopChild(offChild);
      }
    }

    for (const provider of catalog) {
      const credential = env[provider.legacyCredentialEnvKey]
        ?? env[`XPOD_TUNNEL_PROFILE_${provider.id.toUpperCase()}_TOKEN`];
      tunnels.push({
        provider: provider.id,
        credential: fingerprint(credential),
        readiness,
        endpoint: publicEntry,
        detail: credential ? 'credential present' : 'credential absent',
      });
    }
  } catch (error) {
    checks.push({
      id: 'harness',
      entry: 'harness',
      expectation: 'acceptance harness completes',
      observed: 'failed',
      ok: false,
      detail: (error as Error).message,
    });
  } finally {
    qleverFixture?.cleanup();
    await stopChild(child);
  }

  const evidence = {
    schemaVersion: 1,
    kind: 'tunnel-ingress-acceptance',
    candidateSha,
    candidateDirty,
    candidatePort: options.candidatePort,
    candidateLog: path.relative(checkout, logFile),
    envFile: path.relative(checkout, options.envFile),
    storageEngine: qleverFixture ? 'fake-qlever-runtime (fixture)' : 'XPOD_QLEVER_LOCAL_RUNTIME_COMMAND from environment',
    adminTokenFingerprint: fingerprint(adminToken),
    ranAt: new Date().toISOString(),
    checks,
    tunnels,
  };
  writeFileSync(path.join(options.evidenceDir, 'evidence.json'), JSON.stringify(evidence, null, 2));

  const failed = checks.filter((check) => !check.ok);
  for (const check of checks) {
    console.log(`${check.ok ? 'PASS' : 'FAIL'}  ${check.entry}/${check.id}  expected=${check.expectation} observed=${check.observed}`);
  }
  for (const tunnel of tunnels) {
    console.log(`TUNNEL ${tunnel.provider}  credential=${tunnel.credential}  readiness=${tunnel.readiness ?? 'unknown'}  ${tunnel.detail ?? ''}`);
  }
  console.log(`[accept] evidence: ${path.relative(checkout, path.join(options.evidenceDir, 'evidence.json'))}`);
  if (failed.length > 0) {
    console.log(`[accept] ${failed.length} check(s) failed`);
    process.exitCode = 1;
  }
}

await main();
