import type {
  ResourceChangeEvent,
  ResourceChangeListener,
  ResourceChangeRecorder,
} from './ObservableResourceStore';
import type { PostgresRdfSqlExecutor } from './rdf/PostgresRdfSqlExecutor';
import { PgPoolRdfSqlExecutor } from './rdf/PostgresRdfSqlExecutor';
import { getSharedPool, releaseSharedPool } from './database/PostgresPoolManager';

interface JournalRow {
  id: number | string;
  pod_scope_id: string;
  resource_path: string;
  action: ResourceChangeEvent['action'];
  is_container: boolean;
  occurred_at: number | string;
}

export interface DurableResourceChangeConsumer extends ResourceChangeListener {
  readonly consumerId: string;
}

export const LEGACY_DERIVED_INDEX_CONSUMER_ID = 'legacy-resource-change-listener-v1';

export interface PostgresDerivedIndexJournalOptions {
  executor?: PostgresRdfSqlExecutor;
  connectionString?: string;
  resolvePodScope?: (event: ResourceChangeEvent) => string | Promise<string>;
  retryDelayMs?: number;
  leaseMs?: number;
  consumers?: DurableResourceChangeConsumer[];
  pollIntervalMs?: number;
}

export interface DerivedIndexReplayResult {
  delivered: number;
  failed: number;
}

/** PostgreSQL outbox for CSS subscribe events consumed by FTS/VEC derivations. */
export class PostgresDerivedIndexJournal implements ResourceChangeRecorder {
  private readonly options: PostgresDerivedIndexJournalOptions;
  private readonly retryDelayMs: number;
  private readonly leaseMs: number;
  private readonly executor: PostgresRdfSqlExecutor;
  private readonly ownsSharedPool: boolean;
  private readonly consumers: Map<string, DurableResourceChangeConsumer>;
  private readonly activeConsumerIds: Set<string>;
  private opening?: Promise<void>;
  private readonly replaying = new Map<string, Promise<void>>();
  private readonly pollTimer?: ReturnType<typeof setInterval>;

  public constructor(
    connectionString?: string,
    executor?: PostgresRdfSqlExecutor,
    resolvePodScope?: (event: ResourceChangeEvent) => string | Promise<string>,
    retryDelayMs = 1_000,
    leaseMs = 60_000,
    consumers: DurableResourceChangeConsumer[] = [],
    pollIntervalMs = 1_000,
  ) {
    const resolvedOptions: PostgresDerivedIndexJournalOptions = {
      connectionString,
      executor,
      resolvePodScope,
      retryDelayMs,
      leaseMs,
      consumers,
      pollIntervalMs,
    };
    this.options = resolvedOptions;
    if (!resolvedOptions.executor && !resolvedOptions.connectionString) {
      throw new Error('PostgresDerivedIndexJournal requires executor or connectionString');
    }
    const consumerIds = new Set<string>();
    for (const consumer of consumers) {
      if (!consumer.consumerId.trim()) {
        throw new Error('Derived-index consumer requires a non-empty consumerId');
      }
      if (consumerIds.has(consumer.consumerId)) {
        throw new Error(`Duplicate derived-index consumerId: ${consumer.consumerId}`);
      }
      consumerIds.add(consumer.consumerId);
    }
    this.consumers = new Map(consumers.map((consumer) => [consumer.consumerId, consumer]));
    this.activeConsumerIds = new Set(
      consumers.length > 0 ? consumers.map((consumer) => consumer.consumerId) : [LEGACY_DERIVED_INDEX_CONSUMER_ID],
    );
    this.executor = resolvedOptions.executor
      ?? new PgPoolRdfSqlExecutor(getSharedPool({ connectionString: resolvedOptions.connectionString }));
    this.ownsSharedPool = !resolvedOptions.executor;
    this.retryDelayMs = resolvedOptions.retryDelayMs ?? 1_000;
    this.leaseMs = resolvedOptions.leaseMs ?? 60_000;
    if (resolvedOptions.consumers?.length) {
      this.pollTimer = setInterval(() => this.scheduleReplay(), pollIntervalMs);
      this.pollTimer.unref?.();
      setImmediate(() => this.scheduleReplay());
    }
  }

  public async open(): Promise<void> {
    this.opening ??= this.initialize();
    await this.opening;
  }

  private async initialize(): Promise<void> {
    await this.executor.exec(`
      CREATE TABLE IF NOT EXISTS derived_index_change_journal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pod_scope_id TEXT NOT NULL,
        resource_path TEXT NOT NULL,
        action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
        is_container BOOLEAN NOT NULL,
        occurred_at BIGINT NOT NULL,
        stage TEXT NOT NULL DEFAULT 'pending' CHECK (stage IN ('pending', 'processing', 'done')),
        attempts INTEGER NOT NULL DEFAULT 0,
        available_at BIGINT NOT NULL DEFAULT 0,
        lease_until BIGINT,
        last_error TEXT
      );
      CREATE INDEX IF NOT EXISTS derived_index_change_journal_pending
        ON derived_index_change_journal (stage, available_at, pod_scope_id, id);
      CREATE TABLE IF NOT EXISTS derived_index_journal_metadata (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS derived_index_consumers (
        consumer_id TEXT PRIMARY KEY,
        created_at BIGINT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS derived_index_event_deliveries (
        consumer_id TEXT NOT NULL REFERENCES derived_index_consumers(consumer_id),
        event_id BIGINT NOT NULL REFERENCES derived_index_change_journal(id) ON DELETE CASCADE,
        stage TEXT NOT NULL DEFAULT 'pending' CHECK (stage IN ('pending', 'processing', 'done')),
        attempts INTEGER NOT NULL DEFAULT 0,
        available_at BIGINT NOT NULL DEFAULT 0,
        lease_until BIGINT,
        last_error TEXT,
        PRIMARY KEY (consumer_id, event_id)
      );
      CREATE INDEX IF NOT EXISTS derived_index_event_deliveries_pending
        ON derived_index_event_deliveries (consumer_id, stage, available_at, event_id);
      CREATE TABLE IF NOT EXISTS derived_index_resource_checkpoints (
        consumer_id TEXT NOT NULL REFERENCES derived_index_consumers(consumer_id),
        pod_scope_id TEXT NOT NULL,
        resource_path TEXT NOT NULL,
        last_event_id BIGINT NOT NULL REFERENCES derived_index_change_journal(id),
        last_action TEXT NOT NULL CHECK (last_action IN ('create', 'update', 'delete')),
        updated_at BIGINT NOT NULL,
        deleted_at BIGINT,
        PRIMARY KEY (consumer_id, pod_scope_id, resource_path)
      );
    `);
    await this.executor.transaction(async (tx) => {
      const sourceTable = await tx.query<{ relation: string | null }>(`
        SELECT to_regclass('rdf_sources')::text AS relation
      `);
      if (!sourceTable[0]?.relation) return;
      const inserted = await tx.query<{ key: string }>(`
        INSERT INTO derived_index_journal_metadata (key, value)
        VALUES ('rdf_sources_bootstrap_v1', 'complete')
        ON CONFLICT (key) DO NOTHING
        RETURNING key
      `);
      if (!inserted.length) return;
      await tx.exec(`
        INSERT INTO derived_index_change_journal
          (pod_scope_id, resource_path, action, is_container, occurred_at)
        SELECT workspace, source, 'update', FALSE,
               (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint
        FROM rdf_sources
        ORDER BY id
      `);
    });
    const configuredConsumers = this.options.consumers ?? [];
    if (configuredConsumers.length === 0) {
      await this.registerConsumer(LEGACY_DERIVED_INDEX_CONSUMER_ID, true);
    } else {
      for (const consumer of configuredConsumers) {
        await this.registerConsumer(consumer.consumerId, false);
      }
    }
  }

  private async registerConsumer(consumerId: string, legacy: boolean): Promise<void> {
    await this.executor.transaction(async (tx) => {
      const now = Date.now();
      await tx.exec(`
        INSERT INTO derived_index_consumers (consumer_id, created_at)
        VALUES ($1, $2)
        ON CONFLICT (consumer_id) DO NOTHING
      `, [consumerId, now]);
      await tx.exec(`
        INSERT INTO derived_index_event_deliveries
          (consumer_id, event_id, stage, attempts, available_at, lease_until, last_error)
        SELECT $1, id,
               CASE WHEN $2::boolean AND stage = 'done' THEN 'done' ELSE 'pending' END,
               CASE WHEN $2::boolean THEN attempts ELSE 0 END,
               CASE WHEN $2::boolean THEN available_at ELSE 0 END,
               NULL,
               CASE WHEN $2::boolean THEN last_error ELSE NULL END
        FROM derived_index_change_journal
        ON CONFLICT (consumer_id, event_id) DO NOTHING
      `, [consumerId, legacy]);
      if (legacy) {
        await tx.exec(`
          INSERT INTO derived_index_resource_checkpoints
            (consumer_id, pod_scope_id, resource_path, last_event_id,
             last_action, updated_at, deleted_at)
          SELECT $1, latest.pod_scope_id, latest.resource_path, latest.id,
                 latest.action, latest.occurred_at,
                 CASE WHEN latest.action = 'delete' THEN latest.occurred_at ELSE NULL END
          FROM (
            SELECT DISTINCT ON (pod_scope_id, resource_path)
                   id, pod_scope_id, resource_path, action, occurred_at
            FROM derived_index_change_journal
            WHERE stage = 'done'
            ORDER BY pod_scope_id, resource_path, id DESC
          ) latest
          ON CONFLICT (consumer_id, pod_scope_id, resource_path) DO UPDATE
          SET last_event_id = EXCLUDED.last_event_id,
              last_action = EXCLUDED.last_action,
              updated_at = EXCLUDED.updated_at,
              deleted_at = EXCLUDED.deleted_at
          WHERE derived_index_resource_checkpoints.last_event_id < EXCLUDED.last_event_id
        `, [consumerId]);
      }
    });
  }

  public async recordResourceChange(event: ResourceChangeEvent): Promise<void> {
    await this.open();
    const podScopeId = await (this.options.resolvePodScope?.(event) ?? defaultPodScope(event.path));
    if (!podScopeId) {
      throw new Error(`Cannot journal derived-index change without Pod scope: ${event.path}`);
    }
    await this.append(podScopeId, event);
    this.scheduleReplay();
  }

  private async append(podScopeId: string, event: ResourceChangeEvent): Promise<void> {
    await this.executor.transaction(async (tx) => {
      const inserted = await tx.query<{ id: number | string }>(`
        INSERT INTO derived_index_change_journal
          (pod_scope_id, resource_path, action, is_container, occurred_at)
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id
      `, [podScopeId, event.path, event.action, event.isContainer, event.timestamp]);
      const eventId = inserted[0]?.id;
      if (eventId === undefined) {
        throw new Error(`Failed to append derived-index event: ${event.path}`);
      }
      for (const consumerId of this.activeConsumerIds) {
        await tx.exec(`
          INSERT INTO derived_index_event_deliveries (consumer_id, event_id)
          VALUES ($1, $2)
          ON CONFLICT (consumer_id, event_id) DO NOTHING
        `, [consumerId, eventId]);
      }
    });
  }

  public async replayPending(listener: ResourceChangeListener, limit = 100): Promise<DerivedIndexReplayResult> {
    await this.open();
    this.activeConsumerIds.add(LEGACY_DERIVED_INDEX_CONSUMER_ID);
    await this.registerConsumer(LEGACY_DERIVED_INDEX_CONSUMER_ID, true);
    return this.replayDelivery(LEGACY_DERIVED_INDEX_CONSUMER_ID, listener, limit);
  }

  public async replayConsumer(consumerId: string, limit = 100): Promise<DerivedIndexReplayResult> {
    await this.open();
    const consumer = this.consumers.get(consumerId);
    if (!consumer) {
      throw new Error(`Unknown derived-index consumerId: ${consumerId}`);
    }
    return this.replayDelivery(consumerId, consumer, limit);
  }

  private async replayDelivery(
    consumerId: string,
    listener: ResourceChangeListener,
    limit: number,
  ): Promise<DerivedIndexReplayResult> {
    let delivered = 0;
    let failed = 0;
    for (let index = 0; index < limit; index += 1) {
      const row = await this.claimNext(consumerId);
      if (!row) break;
      const event: ResourceChangeEvent = {
        path: row.resource_path,
        action: row.action,
        isContainer: row.is_container,
        timestamp: Number(row.occurred_at),
      };
      try {
        await listener.onResourceChanged(event);
        await this.executor.exec(`
          UPDATE derived_index_event_deliveries
          SET stage = 'done', lease_until = NULL, last_error = NULL
          WHERE consumer_id = $1 AND event_id = $2
        `, [consumerId, row.id]);
        delivered += 1;
      } catch (error) {
        await this.executor.exec(`
          UPDATE derived_index_event_deliveries
          SET stage = 'pending', attempts = attempts + 1,
              available_at = $3, lease_until = NULL, last_error = $4
          WHERE consumer_id = $1 AND event_id = $2
        `, [consumerId, row.id, Date.now() + this.retryDelayMs, errorMessage(error)]);
        failed += 1;
      }
    }
    return { delivered, failed };
  }

  public async reconcilePod(podScopeId: string, resourcePaths: Iterable<string>): Promise<void> {
    for (const resourcePath of resourcePaths) {
      await this.append(podScopeId, {
        path: resourcePath,
        action: 'update',
        isContainer: resourcePath.endsWith('/'),
        timestamp: Date.now(),
      });
    }
  }

  public async pendingCount(podScopeId?: string, consumerId?: string): Promise<number> {
    await this.open();
    const rows = await this.executor.query<{ count: number | string }>(`
      SELECT COUNT(DISTINCT delivery.event_id) AS count
      FROM derived_index_event_deliveries delivery
      JOIN derived_index_change_journal event ON event.id = delivery.event_id
      WHERE delivery.stage <> 'done'
        AND ($1::text IS NULL OR event.pod_scope_id = $1)
        AND (
          ($2::text IS NOT NULL AND delivery.consumer_id = $2)
          OR ($2::text IS NULL AND delivery.consumer_id = ANY($3::text[]))
        )
    `, [podScopeId ?? null, consumerId ?? null, [...this.activeConsumerIds]]);
    return Number(rows[0]?.count ?? 0);
  }

  private async claimNext(consumerId: string): Promise<JournalRow | undefined> {
    return this.executor.transaction(async (tx) => {
      const now = Date.now();
      await tx.exec(`
        UPDATE derived_index_event_deliveries
        SET stage = 'pending', lease_until = NULL
        WHERE consumer_id = $1 AND stage = 'processing' AND lease_until < $2
      `, [consumerId, now]);
      const rows = await tx.query<JournalRow>(`
        SELECT event.id, event.pod_scope_id, event.resource_path, event.action,
               event.is_container, event.occurred_at
        FROM derived_index_event_deliveries delivery
        JOIN derived_index_change_journal event ON event.id = delivery.event_id
        WHERE delivery.consumer_id = $1
          AND delivery.stage = 'pending'
          AND delivery.available_at <= $2
          AND NOT EXISTS (
            SELECT 1
            FROM derived_index_event_deliveries earlier_delivery
            JOIN derived_index_change_journal earlier_event
              ON earlier_event.id = earlier_delivery.event_id
            WHERE earlier_delivery.consumer_id = delivery.consumer_id
              AND earlier_event.pod_scope_id = event.pod_scope_id
              AND earlier_event.id < event.id
              AND earlier_delivery.stage <> 'done'
          )
        ORDER BY event.id
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      `, [consumerId, now]);
      const row = rows[0];
      if (!row) return undefined;
      await tx.exec(`
        UPDATE derived_index_event_deliveries
        SET stage = 'processing', lease_until = $3
        WHERE consumer_id = $1 AND event_id = $2
      `, [consumerId, row.id, now + this.leaseMs]);
      return row;
    });
  }

  public async close(): Promise<void> {
    if (this.pollTimer) clearInterval(this.pollTimer);
    await Promise.all(this.replaying.values());
    if (this.ownsSharedPool && this.options.connectionString) {
      releaseSharedPool({ connectionString: this.options.connectionString });
    }
  }

  private scheduleReplay(): void {
    for (const consumerId of this.consumers.keys()) {
      if (this.replaying.has(consumerId)) continue;
      const replay = this.replayConsumer(consumerId)
        .then(() => undefined)
        .catch(() => undefined)
        .finally(() => { this.replaying.delete(consumerId); });
      this.replaying.set(consumerId, replay);
    }
  }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function defaultPodScope(resourcePath: string): string {
  try {
    const url = new URL(resourcePath);
    const firstSegment = url.pathname.split('/').filter(Boolean)[0];
    return firstSegment ? `${url.origin}/${firstSegment}/` : `${url.origin}/`;
  } catch {
    const firstSegment = resourcePath.split('/').filter(Boolean)[0];
    return firstSegment ?? resourcePath;
  }
}
