import type {
  ResourceChangeEvent,
  ResourceChangeListener,
  ResourceChangeRecorder,
} from './ObservableResourceStore';
import type { PostgresRdfSqlExecutor } from './rdf/PostgresRdfSqlExecutor';
import { PgPoolRdfSqlExecutor } from './rdf/PostgresRdfSqlExecutor';
import { getSharedPool, releaseSharedPool } from './database/PostgresPoolManager';

interface JournalRow {
  id: number | string;
  resource_path: string;
  action: ResourceChangeEvent['action'];
  is_container: boolean;
  occurred_at: number | string;
}

export interface DurableResourceChangeConsumer extends ResourceChangeListener {
  readonly consumerId: string;
}

export const LEGACY_DERIVED_INDEX_CONSUMER_ID = 'legacy-resource-change-listener-v1';

export interface PostgresDerivedIndexJournalOptions {
  executor?: PostgresRdfSqlExecutor;
  connectionString?: string;
  resolvePodScope?: (event: ResourceChangeEvent) => string | Promise<string>;
  retryDelayMs?: number;
  leaseMs?: number;
  consumers?: DurableResourceChangeConsumer[];
  pollIntervalMs?: number;
}

export interface DerivedIndexReplayResult {
  delivered: number;
  failed: number;
}

/** PostgreSQL outbox for CSS subscribe events consumed by FTS/VEC derivations. */
export class PostgresDerivedIndexJournal implements ResourceChangeRecorder {
  private readonly options: PostgresDerivedIndexJournalOptions;
  private readonly retryDelayMs: number;
  private readonly leaseMs: number;
  private readonly executor: PostgresRdfSqlExecutor;
  private readonly ownsSharedPool: boolean;
  private opening?: Promise<void>;
  private replaying?: Promise<void>;
  private readonly pollTimer?: ReturnType<typeof setInterval>;

  public constructor(
    connectionString?: string,
    executor?: PostgresRdfSqlExecutor,
    resolvePodScope?: (event: ResourceChangeEvent) => string | Promise<string>,
    retryDelayMs = 1_000,
    leaseMs = 60_000,
    consumers: DurableResourceChangeConsumer[] = [],
    pollIntervalMs = 1_000,
  ) {
    const resolvedOptions: PostgresDerivedIndexJournalOptions = {
      connectionString,
      executor,
      resolvePodScope,
      retryDelayMs,
      leaseMs,
      consumers,
      pollIntervalMs,
    };
    this.options = resolvedOptions;
    if (!resolvedOptions.executor && !resolvedOptions.connectionString) {
      throw new Error('PostgresDerivedIndexJournal requires executor or connectionString');
    }
    const consumerIds = new Set<string>();
    for (const consumer of consumers) {
      if (!consumer.consumerId.trim()) {
        throw new Error('Derived-index consumer requires a non-empty consumerId');
      }
      if (consumerIds.has(consumer.consumerId)) {
        throw new Error(`Duplicate derived-index consumerId: ${consumer.consumerId}`);
      }
      consumerIds.add(consumer.consumerId);
    }
    this.executor = resolvedOptions.executor
      ?? new PgPoolRdfSqlExecutor(getSharedPool({ connectionString: resolvedOptions.connectionString }));
    this.ownsSharedPool = !resolvedOptions.executor;
    this.retryDelayMs = resolvedOptions.retryDelayMs ?? 1_000;
    this.leaseMs = resolvedOptions.leaseMs ?? 60_000;
    if (resolvedOptions.consumers?.length) {
      this.pollTimer = setInterval(() => this.scheduleReplay(), pollIntervalMs);
      this.pollTimer.unref?.();
      setImmediate(() => this.scheduleReplay());
    }
  }

  public async open(): Promise<void> {
    this.opening ??= this.initialize();
    await this.opening;
  }

  private async initialize(): Promise<void> {
    await this.executor.exec(`
      CREATE TABLE IF NOT EXISTS derived_index_change_journal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pod_scope_id TEXT NOT NULL,
        resource_path TEXT NOT NULL,
        action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
        is_container BOOLEAN NOT NULL,
        occurred_at BIGINT NOT NULL,
        stage TEXT NOT NULL DEFAULT 'pending' CHECK (stage IN ('pending', 'processing', 'done')),
        attempts INTEGER NOT NULL DEFAULT 0,
        available_at BIGINT NOT NULL DEFAULT 0,
        lease_until BIGINT,
        last_error TEXT
      );
      CREATE INDEX IF NOT EXISTS derived_index_change_journal_pending
        ON derived_index_change_journal (stage, available_at, pod_scope_id, id);
      CREATE TABLE IF NOT EXISTS derived_index_journal_metadata (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
      );
    `);
    await this.executor.transaction(async (tx) => {
      const sourceTable = await tx.query<{ relation: string | null }>(`
        SELECT to_regclass('rdf_sources')::text AS relation
      `);
      if (!sourceTable[0]?.relation) return;
      const inserted = await tx.query<{ key: string }>(`
        INSERT INTO derived_index_journal_metadata (key, value)
        VALUES ('rdf_sources_bootstrap_v1', 'complete')
        ON CONFLICT (key) DO NOTHING
        RETURNING key
      `);
      if (!inserted.length) return;
      await tx.exec(`
        INSERT INTO derived_index_change_journal
          (pod_scope_id, resource_path, action, is_container, occurred_at)
        SELECT workspace, source, 'update', FALSE,
               (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::bigint
        FROM rdf_sources
        ORDER BY id
      `);
    });
  }

  public async recordResourceChange(event: ResourceChangeEvent): Promise<void> {
    await this.open();
    const podScopeId = await (this.options.resolvePodScope?.(event) ?? defaultPodScope(event.path));
    if (!podScopeId) {
      throw new Error(`Cannot journal derived-index change without Pod scope: ${event.path}`);
    }
    await this.append(podScopeId, event);
    this.scheduleReplay();
  }

  private async append(podScopeId: string, event: ResourceChangeEvent): Promise<void> {
    await this.executor.exec(`
      INSERT INTO derived_index_change_journal
        (pod_scope_id, resource_path, action, is_container, occurred_at)
      VALUES ($1, $2, $3, $4, $5)
    `, [podScopeId, event.path, event.action, event.isContainer, event.timestamp]);
  }

  public async replayPending(listener: ResourceChangeListener, limit = 100): Promise<DerivedIndexReplayResult> {
    await this.open();
    let delivered = 0;
    let failed = 0;
    for (let index = 0; index < limit; index += 1) {
      const row = await this.claimNext();
      if (!row) break;
      const event: ResourceChangeEvent = {
        path: row.resource_path,
        action: row.action,
        isContainer: row.is_container,
        timestamp: Number(row.occurred_at),
      };
      try {
        await listener.onResourceChanged(event);
        await this.executor.exec(`
          UPDATE derived_index_change_journal
          SET stage = 'done', lease_until = NULL, last_error = NULL
          WHERE id = $1
        `, [row.id]);
        delivered += 1;
      } catch (error) {
        await this.executor.exec(`
          UPDATE derived_index_change_journal
          SET stage = 'pending', attempts = attempts + 1,
              available_at = $2, lease_until = NULL, last_error = $3
          WHERE id = $1
        `, [row.id, Date.now() + this.retryDelayMs, errorMessage(error)]);
        failed += 1;
      }
    }
    return { delivered, failed };
  }

  public async reconcilePod(podScopeId: string, resourcePaths: Iterable<string>): Promise<void> {
    for (const resourcePath of resourcePaths) {
      await this.append(podScopeId, {
        path: resourcePath,
        action: 'update',
        isContainer: resourcePath.endsWith('/'),
        timestamp: Date.now(),
      });
    }
  }

  public async pendingCount(podScopeId?: string): Promise<number> {
    await this.open();
    const rows = await this.executor.query<{ count: number | string }>(`
      SELECT COUNT(*) AS count
      FROM derived_index_change_journal
      WHERE stage <> 'done' AND ($1::text IS NULL OR pod_scope_id = $1)
    `, [podScopeId ?? null]);
    return Number(rows[0]?.count ?? 0);
  }

  private async claimNext(): Promise<JournalRow | undefined> {
    return this.executor.transaction(async (tx) => {
      const now = Date.now();
      await tx.exec(`
        UPDATE derived_index_change_journal
        SET stage = 'pending', lease_until = NULL
        WHERE stage = 'processing' AND lease_until < $1
      `, [now]);
      const rows = await tx.query<JournalRow>(`
        SELECT event.id, event.resource_path, event.action,
               event.is_container, event.occurred_at
        FROM derived_index_change_journal event
        WHERE event.stage = 'pending'
          AND event.available_at <= $1
          AND NOT EXISTS (
            SELECT 1 FROM derived_index_change_journal earlier
            WHERE earlier.pod_scope_id = event.pod_scope_id
              AND earlier.id < event.id
              AND earlier.stage <> 'done'
          )
        ORDER BY event.id
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      `, [now]);
      const row = rows[0];
      if (!row) return undefined;
      await tx.exec(`
        UPDATE derived_index_change_journal
        SET stage = 'processing', lease_until = $2
        WHERE id = $1
      `, [row.id, now + this.leaseMs]);
      return row;
    });
  }

  public async close(): Promise<void> {
    if (this.pollTimer) clearInterval(this.pollTimer);
    await this.replaying;
    if (this.ownsSharedPool && this.options.connectionString) {
      releaseSharedPool({ connectionString: this.options.connectionString });
    }
  }

  private scheduleReplay(): void {
    if (!this.options.consumers?.length || this.replaying) return;
    const listener: ResourceChangeListener = {
      onResourceChanged: async (event) => {
        for (const consumer of this.options.consumers!) {
          await consumer.onResourceChanged(event);
        }
      },
    };
    this.replaying = this.replayPending(listener)
      .then(() => undefined)
      .catch(() => undefined)
      .finally(() => { this.replaying = undefined; });
  }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function defaultPodScope(resourcePath: string): string {
  try {
    const url = new URL(resourcePath);
    const firstSegment = url.pathname.split('/').filter(Boolean)[0];
    return firstSegment ? `${url.origin}/${firstSegment}/` : `${url.origin}/`;
  } catch {
    const firstSegment = resourcePath.split('/').filter(Boolean)[0];
    return firstSegment ?? resourcePath;
  }
}
