import type {
  ResourceChangeEvent,
  ResourceChangeListener,
  ResourceChangeRecorder,
} from './ObservableResourceStore';
import type { PostgresRdfSqlExecutor } from './rdf/PostgresRdfSqlExecutor';

interface JournalRow {
  id: number | string;
  resource_path: string;
  action: ResourceChangeEvent['action'];
  is_container: boolean;
  occurred_at: number | string;
}

export interface PostgresDerivedIndexJournalOptions {
  executor: PostgresRdfSqlExecutor;
  resolvePodScope: (event: ResourceChangeEvent) => string | Promise<string>;
  retryDelayMs?: number;
  leaseMs?: number;
}

export interface DerivedIndexReplayResult {
  delivered: number;
  failed: number;
}

/** PostgreSQL outbox for CSS subscribe events consumed by FTS/VEC derivations. */
export class PostgresDerivedIndexJournal implements ResourceChangeRecorder {
  private readonly retryDelayMs: number;
  private readonly leaseMs: number;

  public constructor(private readonly options: PostgresDerivedIndexJournalOptions) {
    this.retryDelayMs = options.retryDelayMs ?? 1_000;
    this.leaseMs = options.leaseMs ?? 60_000;
  }

  public async open(): Promise<void> {
    await this.options.executor.exec(`
      CREATE TABLE IF NOT EXISTS derived_index_change_journal (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pod_scope_id TEXT NOT NULL,
        resource_path TEXT NOT NULL,
        action TEXT NOT NULL CHECK (action IN ('create', 'update', 'delete')),
        is_container BOOLEAN NOT NULL,
        occurred_at BIGINT NOT NULL,
        stage TEXT NOT NULL DEFAULT 'pending' CHECK (stage IN ('pending', 'processing', 'done')),
        attempts INTEGER NOT NULL DEFAULT 0,
        available_at BIGINT NOT NULL DEFAULT 0,
        lease_until BIGINT,
        last_error TEXT
      );
      CREATE INDEX IF NOT EXISTS derived_index_change_journal_pending
        ON derived_index_change_journal (stage, available_at, pod_scope_id, id);
    `);
  }

  public async recordResourceChange(event: ResourceChangeEvent): Promise<void> {
    const podScopeId = await this.options.resolvePodScope(event);
    if (!podScopeId) {
      throw new Error(`Cannot journal derived-index change without Pod scope: ${event.path}`);
    }
    await this.append(podScopeId, event);
  }

  private async append(podScopeId: string, event: ResourceChangeEvent): Promise<void> {
    await this.options.executor.exec(`
      INSERT INTO derived_index_change_journal
        (pod_scope_id, resource_path, action, is_container, occurred_at)
      VALUES ($1, $2, $3, $4, $5)
    `, [podScopeId, event.path, event.action, event.isContainer, event.timestamp]);
  }

  public async replayPending(listener: ResourceChangeListener, limit = 100): Promise<DerivedIndexReplayResult> {
    let delivered = 0;
    let failed = 0;
    for (let index = 0; index < limit; index += 1) {
      const row = await this.claimNext();
      if (!row) break;
      const event: ResourceChangeEvent = {
        path: row.resource_path,
        action: row.action,
        isContainer: row.is_container,
        timestamp: Number(row.occurred_at),
      };
      try {
        await listener.onResourceChanged(event);
        await this.options.executor.exec(`
          UPDATE derived_index_change_journal
          SET stage = 'done', lease_until = NULL, last_error = NULL
          WHERE id = $1
        `, [row.id]);
        delivered += 1;
      } catch (error) {
        await this.options.executor.exec(`
          UPDATE derived_index_change_journal
          SET stage = 'pending', attempts = attempts + 1,
              available_at = $2, lease_until = NULL, last_error = $3
          WHERE id = $1
        `, [row.id, Date.now() + this.retryDelayMs, errorMessage(error)]);
        failed += 1;
      }
    }
    return { delivered, failed };
  }

  public async reconcilePod(podScopeId: string, resourcePaths: Iterable<string>): Promise<void> {
    for (const resourcePath of resourcePaths) {
      await this.append(podScopeId, {
        path: resourcePath,
        action: 'update',
        isContainer: resourcePath.endsWith('/'),
        timestamp: Date.now(),
      });
    }
  }

  public async pendingCount(podScopeId?: string): Promise<number> {
    const rows = await this.options.executor.query<{ count: number | string }>(`
      SELECT COUNT(*) AS count
      FROM derived_index_change_journal
      WHERE stage <> 'done' AND ($1::text IS NULL OR pod_scope_id = $1)
    `, [podScopeId ?? null]);
    return Number(rows[0]?.count ?? 0);
  }

  private async claimNext(): Promise<JournalRow | undefined> {
    return this.options.executor.transaction(async (tx) => {
      const now = Date.now();
      await tx.exec(`
        UPDATE derived_index_change_journal
        SET stage = 'pending', lease_until = NULL
        WHERE stage = 'processing' AND lease_until < $1
      `, [now]);
      const rows = await tx.query<JournalRow>(`
        SELECT event.id, event.resource_path, event.action,
               event.is_container, event.occurred_at
        FROM derived_index_change_journal event
        WHERE event.stage = 'pending'
          AND event.available_at <= $1
          AND NOT EXISTS (
            SELECT 1 FROM derived_index_change_journal earlier
            WHERE earlier.pod_scope_id = event.pod_scope_id
              AND earlier.id < event.id
              AND earlier.stage <> 'done'
          )
        ORDER BY event.id
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      `, [now]);
      const row = rows[0];
      if (!row) return undefined;
      await tx.exec(`
        UPDATE derived_index_change_journal
        SET stage = 'processing', lease_until = $2
        WHERE id = $1
      `, [row.id, now + this.leaseMs]);
      return row;
    });
  }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
