import { chmodSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { resolveNativeBinary } from './native';
import type { ManagedRoot } from './roots';
import { moduleLauncher } from '../runtime';

export interface InstallRgWrapperOptions {
  dir: string;
  roots: ManagedRoot[];
  nativeRg?: string;
  /** Override the launcher command (executable + entry script). */
  launcher?: string[];
  sessionDir?: string;
}

export interface InstallRgWrapperResult {
  dir: string;
  wrapperPath: string;
  nativeRg: string;
  launcher: string[];
}

export function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function resolveLauncher(override?: string[]): string[] {
  if (override && override.length > 0) {
    return override;
  }
  return moduleLauncher();
}

export function installRgWrapper(options: InstallRgWrapperOptions): InstallRgWrapperResult {
  const dir = path.resolve(options.dir);
  mkdirSync(dir, { recursive: true });

  const nativeRg = options.nativeRg ?? resolveNativeBinary('rg', process.env, [ dir ]);
  if (!nativeRg) {
    throw new Error('Could not resolve a native rg binary. Pass --native-rg or install ripgrep.');
  }
  const launcher = resolveLauncher(options.launcher);

  const rootsJson = JSON.stringify(options.roots);
  const wrapperPath = path.join(dir, 'rg');
  const script = [
    '#!/bin/sh',
    '# Generated by `xpod agent-fs install`. Session-scoped rg wrapper.',
    'XPOD_AGENT_FS_WRAPPER_DIR="$(cd "$(dirname "$0")" && pwd)"',
    'export XPOD_AGENT_FS_WRAPPER_DIR',
    `export XPOD_AGENT_FS_NATIVE_RG=${shellQuote(nativeRg)}`,
    `export XPOD_AGENT_FS_ROOTS=${shellQuote(rootsJson)}`,
    ...(options.sessionDir ? [ `export XPOD_AGENTFS_SESSION=${shellQuote(path.resolve(options.sessionDir))}` ] : []),
    `exec ${launcher.map(shellQuote).join(' ')} rg "$@"`,
    '',
  ].join('\n');
  writeFileSync(wrapperPath, script, 'utf8');
  chmodSync(wrapperPath, 0o755);

  return { dir, wrapperPath, nativeRg, launcher };
}

export function renderEnvExports(result: InstallRgWrapperResult): string[] {
  return [
    `export XPOD_AGENT_FS_WRAPPER_DIR=${shellQuote(result.dir)}`,
    `export XPOD_AGENT_FS_NATIVE_RG=${shellQuote(result.nativeRg)}`,
    `export PATH=${shellQuote(result.dir)}:"$PATH"`,
  ];
}
