apiVersion: v1
kind: ConfigMap
metadata:
  name: xpod-rc-config
  namespace: xpod-rc
data:
  NODE_ENV: production
  XPOD_EDITION: cloud
  XPOD_PORT: "3000"
  CSS_PORT: "6300"
  API_PORT: "6301"
  CSS_LOGGING_LEVEL: info

  CSS_BASE_URL: https://undefineds-gz-rc-id.sealosgzg.site
  CSS_ALLOWED_HOSTS: undefineds-gz-rc-id.sealosgzg.site,undefineds-gz-rc-pods.sealosgzg.site,undefineds-gz-rc-api.sealosgzg.site
  XPOD_PUBLIC_API_URL: https://undefineds-gz-rc-api.sealosgzg.site

  XPOD_EDGE_NODES_ENABLED: "false"
