apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xpod-rc
resources:
  - configmap.yaml
  - certificates.yaml
  - deployment.yaml
  - service.yaml
  - inngest-deployment.yaml
  - inngest-service.yaml
  - ingress.yaml
