export { RdfTermDictionary } from './RdfTermDictionary';
export {
  RDF_NUMERIC_DATATYPES,
  isFiniteNumericLexical,
  isRdfNumericDatatype,
  isRdfNumericTerm,
  rdfNumericValue,
} from './RdfTermSemantics';
export { RdfQuadIndex } from './RdfQuadIndex';
export { Rdf3xIndex } from './Rdf3xIndex';
export { RDF_TEXT_SCHEMA_VERSION, RdfTextIndex, tokenizeNormalizedRdfText } from './RdfTextIndex';
export {
  createRdfEntityTextChunks,
  createRdfEntityTextChunksFromText,
  parseRdfTextProjectionQuads,
  rdfTextIndexPolicyRole,
  type TextIndexPolicyRole,
} from './RdfTextProjection';
export {
  PostgresRdfTextIndex,
  type PostgresRdfTextIndexOptions,
  type PostgresRdfTextSearchBackend,
} from './PostgresRdfTextIndex';
export { RdfVectorIndex } from './RdfVectorIndex';
export { PostgresRdfVectorIndex, type PostgresRdfVectorIndexOptions } from './PostgresRdfVectorIndex';
export {
  isLineAddressableRdf,
  isLineAddressableRdfContentType,
  isLineAddressableRdfPath,
  isRdfDocument,
  isRdfDocumentContentType,
  isRdfDocumentPath,
  isSafeRdfDocumentContentType,
  normalizeContentType,
  rdfContentTypeForPath,
} from './RdfContentTypes';
export { RdfShadowComparator, canonicalQuadKey, diffQuads } from './RdfShadowComparator';
export { RdfQueryExecutor, variable as rdfVar } from './RdfQueryExecutor';
export {
  applyRdfAccessScope,
  filterRdfAccessGraphs,
  isRestrictiveRdfAccessScope,
  rdfAccessCacheScope,
  rdfAccessGraphAllowed,
  type RdfAccessMode,
  type RdfAccessScope,
} from './RdfAccessScope';
export { ShadowRdfQuintStore, type ShadowRdfQuintStoreOptions } from './ShadowRdfQuintStore';
export { SolidRdfEngine, type SolidRdfEngineOptions } from './SolidRdfEngine';
export {
  PostgresRdfEngine,
  type PostgresRdfEngineOptions,
} from './PostgresRdfEngine';
export {
  DisabledSparqlFeatureError,
  NativeSparqlExecutionError,
  RdfSparqlAdapter,
  UnsupportedSparqlQueryError,
  sparqlCorrectionForCapability,
  type RdfSparqlCompileResult,
  type RdfSparqlDeleteOperation,
  type RdfSparqlDeleteWhereOperation,
  type RdfSparqlDeleteWhereTemplate,
  type RdfSparqlInsertOperation,
  type RdfSparqlUpdateDelta,
  type RdfSparqlUpdateDeltaOperation,
  type SparqlCorrection,
  type SparqlCorrectionAction,
  type SparqlCorrectionTarget,
} from './RdfSparqlAdapter';
export {
  SolidRdfSparqlEngine,
  type SolidRdfSparqlEngineOptions,
  type SolidRdfSparqlFallback,
  type SolidRdfSparqlFallbackMetric,
  type SolidRdfSparqlMetricsSnapshot,
  type SolidRdfSparqlOperation,
  type SolidRdfSparqlOperationCount,
  type SolidRdfSparqlPrimaryMetric,
} from './SolidRdfSparqlEngine';
export {
  rdfModelsBenchmarkCases,
  rdfModelsBenchmarkCaseNames,
  rdfModelsBenchmarkCasesForProfile,
  rdfModelsExtremeBenchmarkCases,
  rdfModelsExtremeBenchmarkCaseNames,
  rdfModelsExtremeQueryBenchmarkCases,
  rdfModelsExtremeQueryBenchmarkCaseNames,
  rdfModelsPostgresMaterializedQueryBenchmarkCases,
  rdfModelsPostgresMaterializedQueryBenchmarkCaseNames,
  rdfModelsPostgresQueryBenchmarkCases,
  rdfModelsPostgresQueryBenchmarkCaseNames,
  rdfModelsPostgresQueryBenchmarkCasesForProfile,
  rdfModelsQueryBenchmarkCases,
  rdfModelsQueryBenchmarkCaseNames,
  rdfModelsQueryBenchmarkCasesForProfile,
  rdfModelsSearchFusionQueryBenchmarkCases,
  rdfModelsSearchFusionQueryBenchmarkCaseNames,
  RDF_MODELS_BENCHMARK_POD,
  buildRdfModelsBenchmarkSeed,
  defaultSyntheticMessagesForRdfModelsScale,
  estimateRdfModelsSyntheticQuadCount,
  syntheticMessagesForRdfModelsTargetQuads,
  rdfModelsBenchmarkProfileRequiresSearchFusion,
  rdfModelsBenchmarkScaleSatisfied,
  rdfModelsBenchmarkTargetSatisfied,
  rdfModelsBenchmarkSyntheticPodCount,
  rdfModelsBenchmarkScaleTargetQuads,
  rdfModelsSearchFusionBroadSourceCountForScale,
  runRdfModelsBenchmark,
  runRdfModelsPostgresBenchmark,
  runRdfModelsRdf3xShadowBenchmark,
  runRdfModelsShadowBenchmark,
  seedRdfModelsSearchFusionIndexes,
  RDF_MODELS_SYNTHETIC_MESSAGE_QUADS,
  type RdfBenchmarkCaseProfile,
  type RdfBenchmarkScale,
  type RdfModelBenchmarkCase,
  type RdfModelQueryBenchmarkCase,
  type RdfModelQueryBenchmarkResult,
  type RdfModelBenchmarkReport,
  type RdfModelBenchmarkResult,
  type RdfModelBenchmarkRunOptions,
  type RdfModelPostgresConcurrencyGate,
  type RdfModelPostgresConcurrencyGateCase,
  type RdfModelPostgresBenchmarkReport,
  type RdfModelPostgresBenchmarkGateBaseline,
  type RdfModelPostgresBenchmarkGateCaseThresholds,
  type RdfModelPostgresBenchmarkGateThresholds,
  type RdfModelPostgresBenchmarkRunOptions,
  type RdfModelPostgresColdStartBenchmark,
  type RdfModelPostgresColdStartQueryBenchmark,
  type RdfModelPostgresPostWriteRefreshBenchmark,
  type RdfModelPostgresRefreshBenchmark,
  type RdfModelPostgresWarmSteadyStateBenchmark,
  type RdfModelsBenchmarkSeedOptions,
  type RdfModelShadowBenchmarkReport,
  type RdfModelRdf3xShadowBenchmarkReport,
  type RdfModelRdf3xShadowJoinBenchmarkResult,
  type RdfModelRdf3xShadowBenchmarkResult,
  type RdfModelShadowBenchmarkResult,
  type RdfModelShadowBenchmarkRunOptions,
  type RdfModelShadowBenchmarkSide,
} from './models-benchmark';
export type {
  RdfEngineLike,
  RdfEngineColdStartPhaseStats,
  RdfEngineColdStartStats,
  RdfEngineLifecycleStats,
  RdfEngineStorageStats,
  RdfStorageStatsOptions,
  RdfDerivedCacheScopeStatsOptions,
  RdfDerivedIndexMaintenanceResult,
  RdfDerivedIndexRefreshResult,
  RdfPlannerStatsRefreshResult,
  RdfIndexStats,
  RdfDerivedIndexProfile,
  RdfPgAccelerationFallbackReason,
  RdfPgAccelerationProfile,
  RdfPgAccelerationStats,
  Rdf3xCardinalityEstimate,
  Rdf3xCountResult,
  Rdf3xJoinMetrics,
  Rdf3xJoinOptions,
  Rdf3xJoinScanResult,
  Rdf3xIndexMetrics,
  Rdf3xIndexStats,
  Rdf3xObjectOperatorPattern,
  Rdf3xObjectRangePattern,
  Rdf3xPairProjectionName,
  Rdf3xPatternKey,
  Rdf3xPermutationName,
  Rdf3xRebuildResult,
  Rdf3xTermKey,
  Rdf3xTermInPattern,
  Rdf3xTermMetadataPattern,
  Rdf3xTermNotInPattern,
  Rdf3xTermProjectionName,
  Rdf3xTermTypePatternValue,
  Rdf3xIndexOptions,
  Rdf3xTriplePattern,
  Rdf3xTripleScanOptions,
  Rdf3xTripleScanResult,
  Rdf3xShadowBindingDiff,
  Rdf3xShadowQuadDiff,
  Rdf3xShadowJoinResult,
  Rdf3xShadowScanResult,
  RdfIndexSpaceObject,
  RdfIndexMetrics,
  RdfIndexPutOptions,
  RdfBoundedPath,
  RdfBoundedPathEdge,
  RdfBoundedPathSearchOptions,
  RdfBoundedPathSearchResult,
  RdfBindingRow,
  RdfMaterializedViewBindingSource,
  RdfMaterializedViewActivationInput,
  RdfMaterializedViewActivationResult,
  RdfMaterializedViewBuildInput,
  RdfMaterializedViewBuildResult,
  RdfMaterializedViewReadResult,
  RdfNativeSparqlAccessScope,
  RdfNativeSparqlQueryOptions,
  RdfNativeSparqlResult,
  RdfConstructTemplate,
  RdfQuadJoinOptions,
  RdfQuadJoinCountOptions,
  RdfQuadJoinOrder,
  RdfQuadJoinPattern,
  RdfQuadJoinScanResult,
  RdfQuery,
  RdfQueryAggregate,
  RdfQueryMetrics,
  RdfQueryResult,
  RdfPatternQuery,
  RdfQuadIndexOptions,
  RdfQuadIndexScanResult,
  RdfQuadRow,
  RdfQueryOrder,
  RdfQueryPattern,
  RdfQueryPatternKey,
  RdfQueryTermPattern,
  RdfQueryVariable,
  RdfPathEdgeDirection,
  RdfPathSearchDirection,
  RdfSchemaExplorerOptions,
  RdfSchemaExplorerResult,
  RdfSchemaExplorerTermEntry,
  RdfShadowBackfillOptions,
  RdfShadowBackfillResult,
  RdfShadowDiff,
  RdfShadowScanResult,
  RdfSourceInput,
  RdfSourceRow,
  RdfTextChunkInput,
  RdfTextChunkRow,
  RdfTextIndexLike,
  RdfTextIndexOptions,
  RdfTextIndexSyncLike,
  RdfTextIndexStats,
  RdfTextRebuildStatus,
  RdfTextRebuildStatusInput,
  RdfTextRebuildStatusKind,
  RdfTextSearchOptions,
  RdfTextSearchPattern,
  RdfTextSearchResult,
  RdfTextSourceInput,
  RdfTextSourceMetadata,
  RdfTextTermDocumentFrequency,
  RdfVectorChunkInput,
  RdfVectorChunkRow,
  RdfVectorDistanceMetric,
  RdfVectorIndexLike,
  RdfVectorIndexOptions,
  RdfVectorIndexSyncLike,
  RdfVectorIndexStats,
  RdfVectorModelDistribution,
  RdfVectorSearchOptions,
  RdfVectorSearchPattern,
  RdfVectorSearchResult,
  RdfVectorSourceInput,
  RdfVectorSummaryLifecycleEntry,
  RdfVectorSummaryLifecycleOptions,
  RdfVectorSummaryMetadata,
  RdfTermKind,
  RdfTermLookup,
  RdfTermRow,
  RdfTermRewriteInput,
  RdfTermRewriteMode,
  RdfTermRewriteResult,
  RdfTermRewriteScope,
  RdfTermRewriteSkippedTerm,
  RdfTermSelection,
} from './types';
